export const MAIN_SCREEN = "MAIN_SCREEN";

export enum NEXT_SCREENS {
    ONE = "NEXT_SCREENS_ONE",
    TWO = "NEXT_SCREENS_TWO",
    THREE = "NEXT_SCREENS_THREE",
}

export enum EXAMPLE_SCREENS {
    ONE = "EXAMPLE_SCREENS_ONE",
    TWO = "EXAMPLE_SCREENS_TWO",
    THREE = "EXAMPLE_SCREENS_THREE",
}

export enum CHAT_SCREENS {
    LOGIN = "CHAT_SCREENS_LOGIN",
    MAIN = "CHAT_SCREENS_MAIN",
}
